import { Pair } from "../../Util";
import { Area } from "./Area";
import { World } from "./World";

export const Worlds = {
    WizardCity: new World("Wizard City", 39, new Pair(0, 5), "wc", [
        new Area("Unicorn Way"),
        new Area("Cyclops Lane"),
        new Area("Firecat Alley"),
        new Area("Triton Avenue"),
    ]),
    Krokotopia: new World("Krokotopia", 65, new Pair(5, 15), "kt", [
        new Area("Royal Hall"),
        new Area("Chamber of Fire"),
        new Area("Palace of Fire"),
        new Area("Hall of Champions"),
        new Area("Grand Arena"),
        new Area("Entrance Hall"),
        new Area("Tomb of Storms")
    ]),
    Marleybone: new World("Marleybone", 50, new Pair(15, 20), "mb", [
        new Area("Hyde Park"),
        new Area("Chelsea Court"),
        new Area("Ironworks"),
        new Area("Newgate Prison"),
        new Area("Knight's Court"),
        new Area("Katzenstein's Lab"),
        new Area("Royal Museum")
    ]),
    MooShu: new World("MooShu", 88, new Pair(20, 30), "ms", [
        new Area("Jade Palace"),
        new Area("Hametsu Village"),
        new Area("Tatakai Outpost"),
        new Area("Crimson Fields"),
        new Area("Cave of Solitude"),
        new Area("Kishibe Village"),
        new Area("Shirataki Temple"),
        new Area("Ancient Burial Grounds"),
        new Area("Village of Sorrow"),
        new Area("Yoshihito Temple"),
        new Area("Emperor's Throne Room")
    ]),
    Dragonspyre: new World("Dragonspyre", 106, new Pair(30, 40), "ds", [
        new Area("The Tower Archives"),
        new Area("Plaza of Conquests"),
        new Area("The Drake Hatchery"),
        new Area("The Crucible"),
        new Area("The Labyrinth"),
        new Area("Dragonspyre Academy"),
        new Area("Crystal Grove"),
        new Area("The Forum"),
        new Area("Dragon's Roost")
    ]),
    Celestia: new World("Celestia", 95, new Pair(40, 50), "cl", [
        new Area("Survey Camp"),
        new Area("The Grotto"),
        new Area("District of the Stars"),
        new Area("The Floating Land"),
        new Area("Stormriven"),
        new Area("Science Center"),
        new Area("Crustacean Empire"),
        new Area("The Chancel"),
        new Area("Sanctum of the Sun")
    ]),
    Zafaria: new World("Zafaria", 148, new Pair(50, 60), "zf", [
        new Area("Baobab Crossroads"),
        new Area("Baobab Crown"),
        new Area("Savannah"),
        new Area("Zamunda Outskirts"),
        new Area("Zamunda"),
        new Area("Stone Town"),
        new Area("Waterfront"),
        new Area("Drum Jungle"),
        new Area("Elephant Graveyard"),
        new Area("Mirror Lake")
    ]),
    Avalon: new World("Avalon", 161, new Pair(60, 70), "av", [
        new Area("High Road"),
        new Area("Caer Lyon"),
        new Area("The Wild"),
        new Area("The Wyrd"),
        new Area("Dun Dara"),
        new Area("Outer Yard"),
        new Area("Lake Shore"),
        new Area("Deepwater"),
        new Area("The Catacombs"),
        new Area("Crystal Caves")
    ]),
    Azteca: new World("Azteca", 197, new Pair(70, 80), "at", [
        new Area("The Zocalo"),
        new Area("Three Points"),
        new Area("Cenote"),
        new Area("Mangrove Marsh"),
        new Area("Saltmeadow Swamp"),
        new Area("Zultun Dock"),
        new Area("Cloudburst Forest"),
        new Area("Alto Alto"),
        new Area("Tierra de Brea"),
        new Area("Pitch Black Lake"),
        new Area("Floating Mountains"),
        new Area("Twin Giants"),
        new Area("Xibalba")
    ]),
    Khrysalis: new World("Khrysalis", 277, new Pair(80, 100), "kr", [
        new Area("Bastion"),
        new Area("Silent Market"),
        new Area("Moon Cliffs"),
        new Area("Last Wood"),
        new Area("Tyrian Gorge"),
        new Area("Fort Rachias"),
        new Area("Crescent Beach"),
        new Area("Ruined Alcazar"),
        new Area("Radiance Reborn"),
        new Area("Sardonyx"),
        new Area("Kondha Desert"),
        new Area("Solar Arc"),
        new Area("The Hive"),
        new Area("Shadow Palace")
    ]),
    Polaris: new World("Polaris", 99, new Pair(100, 110), "pl", [
        new Area("Walruskberg"),
        new Area("Walruskberg Harbor"),
        new Area("Forlorn Tayg"),
        new Area("River of Frozen Tears"),
        new Area("Urville Station"),
        new Area("Frigid Maw"),
        new Area("The Arcanum"),
        new Area("Kataba IceBlock"),
        new Area("Borealis Peaks"),
        new Area("Horizon Hold")
    ]),
    Mirage: new World("Mirage", 115, new Pair(110, 120), "mr", [
        new Area("Caravan"),
        new Area("Alkali Barrows"),
        new Area("Aggrobah"),
        new Area("Caterwaul Canyons"),
        new Area("Rubal Wastes"),
        new Area("Istanboa"),
        new Area("Yakhal Mountain"),
        new Area("Thieve's Den"),
        new Area("Eerem Palace"),
        new Area("Chronoverge")
    ]),
    Empyrea: new World("Empyrea", 149, new Pair(120, 130), "em", [
        new Area("Aerial Shores"),
        new Area("Aerial Jungle"),
        new Area("Zanadu"),
        new Area("Zanadu Sewers"),
        new Area("Outer Athanor"),
        new Area("Inner Athanor"),
        new Area("Sepidious"),
        new Area("Samsara Village"),
        new Area("Mandalla"),
        new Area("Nexus (Reverie)"),
        new Area("Nimbus Citadel"),
        new Area("Port Aero"),
        new Area("Southwest Aeroplains"),
        new Area("Velo City"),
        new Area("Northeast Aeroplains"),
        new Area("Chaos Jungle"),
        new Area("Husk"),
        new Area("Storm Titan's Wake"),
    ]),
    Karamelle: new World("Karamelle", 80, new Pair(130, 140), "ka", [
        new Area("Karamelle City"),
        new Area("Rock Candy Mountains"),
        new Area("Gumdrop Forest"),
        new Area("Sweetzburg"),
        new Area("Nibbleheim"),
        new Area("Gutenstadt"),
        new Area("Gobblerton"),
        new Area("Licorice Forest"),
        new Area("Cavity Chamber")
    ]),
    Grizzleheim: new World('Grizzleheim', 68, new Pair(20, 45), 'gh', []),
    Wintertusk: new World('Wintertusk', 51, new Pair(45, 55), 'wt', [])
}